### PR TITLE
generated all sphinx docs via numpydoc

### PR DESCRIPTION
**Pull request by weiwzhang**
See all documentation files (.html) in config/_build/html/api. Feel free to contact us (Weiwei/Pearl) about any revision. thx!

### CODE REVIEW

**Comment by stefanv** [comment]
Can you please remove all auto-generated files?

**Comment by stefanv** [comment]
- Please do not commit any built files!
- Add doc building to the Travis tests

**Comment by stefanv** [comment]
This PR still contains a bunch of files it shouldn't.

**Comment by weiwzhang** [comment]
I did delete all the auto-generated files for the most recent commit? Let me do it again!

**Pull request closed without merging**
